account_id="762f63023e996841c31645809a90c1d0"
compatibility_date="2023-05-01"
main="index.ts"
name="blog-note"

[[routes]]
pattern="atoz.ltd"
custom_domain=true

[[routes]]
zone_id="b892eb8864058dab1d6dcf29348de276"
pattern="atoz.ltd/note/*"

[[d1_databases]]
database_id="71841805-96d5-4fe6-9d6a-ea1f73c231b6"
database_name="blog_d7c24df"
binding="DB"

[[kv_namespaces]]
preview_id="dd230fae3167431bb249f9a05e8c33b3"
id="dd230fae3167431bb249f9a05e8c33b3"
binding="KV"

[[r2_buckets]]
preview_bucket_name="static-1c88a"
bucket_name="static-1c88a"
binding="R2Static"
