account_id="762f63023e996841c31645809a90c1d0"
compatibility_date="2023-05-01"
main="index.ts"
name="blog-master"

[[routes]]
pattern="atoz.ltd"
custom_domain=true

[[routes]]
zone_id="b892eb8864058dab1d6dcf29348de276"
pattern="atoz.ltd/master/*"

[[d1_databases]]
database_id="85794dcb-0a40-4ac4-9110-a923ceea31cb"
database_name="blog_16bb835"
binding="DB"

[[kv_namespaces]]
preview_id="9ca83df5bf974bc7b52f7723d558f3d5"
id="9ca83df5bf974bc7b52f7723d558f3d5"
binding="KV"

[[r2_buckets]]
preview_bucket_name="static-0da64"
bucket_name="static-0da64"
binding="R2Static"
