name="blog"
main="index.ts"
compatibility_date="2023-05-01"

[[d1_databases]]
binding="DB"
database_name="blog_16bb835"
database_id="85794dcb-0a40-4ac4-9110-a923ceea31cb"

[[kv_namespaces]]
binding="KV"
id="9ca83df5bf974bc7b52f7723d558f3d5"
preview_id="9ca83df5bf974bc7b52f7723d558f3d5"
